[ISSUE 4] Added --sim_id argument to subliminal-test, which can take a simulator UDID provided by simctl.

diff --git a/Supporting Files/CI/subliminal-test b/Supporting Files/CI/subliminal-test
--- a/Supporting Files/CI/subliminal-test
+++ b/Supporting Files/CI/subliminal-test
@@ -28,7 +28,7 @@
 print_usage_and_fail () {
 	echo """
 subliminal-test (-project <project_path> | -workspace <workspace_path> | -prebuilt_app <app_path>)
-		( -sim_device <device_type> | -hw_id <udid> )
+		( -sim_device <device_type> | -sim_id <udid> | -hw_id <udid> )
 		[-build_tool <tool_name>] [-scheme <scheme_name>] [-sdk <sdk>] [-replacement_bundle_id <id>] [--quiet_build]
 		[-sim_version <version>] [-timeout <timeout>] [-output <output_dir>] 
 		[-e <variable> <value>]
@@ -59,15 +59,15 @@ the server will not be able to autocreate the scheme, as you may have done local
 
 Required arguments:
 	-project <project_path>		Build the project at the specified path.
-					Either this, \`-workspace\`, or \'-prebuilt-app\' must be specified.
+					Either this, \`-workspace\`, or \`-prebuilt-app\` must be specified.
 
 	-workspace <workspace_path>	Build the workspace at the specified path.
-					Either this, \`-project\`, or \'prebuilt-app\' must be specified.
+					Either this, \`-project\`, or \`prebuilt-app\` must be specified.
 
         -prebuilt_app <path_to_app>	Use the APP at the specified path, rather than building a new one.
-					If it was built for iphoneos, then -hw_id must be used.
-					If it was built for iphonesimulator, then -sim_device must be used.
-					Either this, \`-project\`, or \'-workspace\' must be specified.
+					If it was built for iphoneos, then \`-hw_id\` must be used.
+					If it was built for iphonesimulator, then \`-sim_device\` or \`-sim_id\` must be used.
+					Either this, \`-project\`, or \`-workspace\` must be specified.
 
 	-sim_device <device_type>	The type of device to simulate.
 					Acceptable values are listed by executing \`instruments -s devices\`:
@@ -85,10 +85,16 @@ Required arguments:
 					certain combinations  of device type and SDK (as specified using the
 					\`-sim_version\` argument), e.g. \"iPhone\" and \"7.1\".
 
-					Either this or \`-hw_id\` must be specified.
+					Either this, \`-sim_id\` or \`-hw_id\` must be specified.
+
+	-sim_id <udid>			The UDID of the simulator to target.
+					This value is provided by \`simctl\` for each simulator/os pair, and is usable only
+					with Xcode 6. 
+
+					Either this, \`-sim_device\`, or \`-hw_id\` must be specified.
 
 	-hw_id <udid>			The UDID of the hardware to target.
-					Either this or \`-sim_device\` must be specified.
+					Either this, \`-sim_id\` or \`-sim_device\` must be specified.
 
 Optional build arguments:
 	-build_tool <tool_name>		The tool to use to build the scheme. Should be either \"xcrun xcodebuild\" 
@@ -101,10 +107,10 @@ Optional build arguments:
 					Defaults to \"Release\".
 
 	-sdk <sdk>			The SDK to use to build the specified project or workspace.
-					This should be an iOS Simulator SDK if \`-sim_device\` is specified, 
+					This should be an iOS Simulator SDK if \`-sim_device\` or \`-sim_id\` is specified, 
 					or an iOS device SDK if \`-hw_id\` is specified. Defaults to 
 					\"iphonesimulator\" (the latest iOS Simulator SDK installed) 
-					if \`-sim_device\` is specified, or \"iphoneos\" (the latest 
+					if \`-sim_device\` or \`-sim_id\` is specified, or \"iphoneos\" (the latest 
 					iOS device SDK) if \`-hw_id\` is specified.
 
 	-replacement_bundle_id <id>	The identifier to use to overwrite the product's bundle identifier.
@@ -165,24 +171,10 @@ SCHEME="Integration Tests"
 CONFIGURATION="Release"
 ENV_STR=""
 
-LOGIN_PASSWORD_DEPRECATION_MESSAGE="""\n
-WARNING: The \`--live\` and \`-login_password\` options have been deprecated\n
-as of Subliminal 1.1. https://github.com/inkling/Subliminal/wiki/Continuous-Integration#faq\n
-describes how to \"pre-authorize\" \`instruments\` so that \`subliminal-test\`\n
-may run un-attended without the current user's login password.\n
-\n
-In an upcoming release, \`subliminal-instrument\` will reject the \`--live\` and\n
-\`-login_password\` options and require that \`instruments\` be pre-authorized.
-"""
-
 while :
 do
 case $1 in
 	# Must check these before the single dash options (because -* would match them)
-	--live)
-		echo $LOGIN_PASSWORD_DEPRECATION_MESSAGE
-		shift 1;;
-
     --quiet_build)
 		QUIET_BUILD=true
 		shift 1;;
@@ -192,7 +184,7 @@ case $1 in
 		shift 1;;
 
 	# Set argument, wait for value
-	-project|-workspace|-prebuilt_app|-sim_device|-hw_id|-build_tool|-scheme|-configuration|-sdk|-replacement_bundle_id|-sim_version|-timeout|-output|-e)
+	-project|-workspace|-prebuilt_app|-sim_device|-sim_id|-hw_id|-build_tool|-scheme|-configuration|-sdk|-replacement_bundle_id|-sim_version|-timeout|-output|-e)
 		if [[ -n "$CURRENT_ARG" ]]; then
 			echo "Missing value for argument: $CURRENT_ARG"
 			print_usage_and_fail
@@ -203,13 +195,6 @@ case $1 in
 			# Variables (apart from env vars) are capitalized in this script
 			*)	CURRENT_ARG=`echo ${1#-} | tr [[:lower:]] [[:upper:]]`;;
 		esac
-		shift 1;;
-
-	-login_password)
-		echo $LOGIN_PASSWORD_DEPRECATION_MESSAGE
-		# While `-login_password` is deprecated, we still need to use it (if present)
-		# to try to authorize `instruments` in case the user has not yet pre-authorized `instruments`
-		CURRENT_ARG=LOGIN_PASSWORD
 		shift 1;;
 
 	-*)
@@ -258,8 +243,16 @@ fi
 
 # Enforce required args
 if [[ ( -z "$PROJECT" && -z "$WORKSPACE" && -z "$PREBUILT_APP" ) ||
-	  ( -z "$SIM_DEVICE" && -z "$HW_ID" ) ]]; then
+	  ( -z "$SIM_DEVICE" && -z "$SIM_ID" && -z "$HW_ID" ) ]]; then
 	echo "Missing required arguments"
+	print_usage_and_fail
+fi
+
+# Check for Xcode 6
+IS_XCODE6=`[[ "$(xcrun xcodebuild -version | head -n 1)" == "Xcode 6"* ]] && echo $?`
+
+if [[ -n "$SIM_ID" && ! $IS_XCODE6 ]]; then
+	echo "Error: Using \`sim_id\` with unsupported Xcode version."
 	print_usage_and_fail
 fi
 
@@ -270,7 +263,15 @@ fi
 reset_simulator_or_device () {
 	local reset_success=0
 	
-	if [[ -n "$SIM_DEVICE" ]]; then
+	if [[ -n "$SIM_ID" ]]; then
+		"$SCRIPT_DIR/simulator-set" --id "$SIM_ID" --reset
+		reset_success=$?
+		if [[ $reset_success -eq 0 ]]; then
+			echo "Successfully reset iOS Simulator."
+		else
+			echo "\nERROR: Could not reset the simulator."
+		fi
+	elif [[ -n "$SIM_DEVICE" ]]; then
 		# Make sure to maintain the previously set device type/version
 		"$SCRIPT_DIR/simulator-set" --device "$SIM_DEVICE" --version "$SIM_VERSION" --reset
 		reset_success=$?
@@ -374,7 +375,7 @@ QUIETLY=`([[ -n "$QUIET_BUILD" ]] && $QUIET_BUILD) && echo " (quietly)" || echo 
 echo "\n\nBuilding app$QUIETLY..."
 
 if [[ -z "$SDK" ]]; then
-	SDK=`[[ -n "$SIM_DEVICE" ]] && echo "iphonesimulator" || echo "iphoneos"`
+	SDK=`[[ -n "$SIM_DEVICE" || -n "$SIM_ID" ]] && echo "iphonesimulator" || echo "iphoneos"`
 fi
 
 # This is a function so that it may be called again if instruments hiccups; see below.
@@ -469,7 +470,7 @@ build_app
 ### (Prepare to) install app
 echo "\n\nPreparing to install app..."
 
-if [[ -n "$SIM_DEVICE" ]]; then
+if [[ -n "$SIM_DEVICE" || -n "$SIM_ID" ]]; then
 	# Configure the simulator's properties
 	echo "\nConfiguring the simulator for testing..."
 
@@ -480,13 +481,12 @@ if [[ -n "$SIM_DEVICE" ]]; then
 		echo "- Setting the version to $SIM_VERSION (Simulator version not specified--defaulting to latest simulator installed)"
 	fi
 
-	# We don't strictly need to set the device type here--instruments uses whatever
-	# device is specified when it is launched, not what was previously in use
-	# --but it's nice to see in the logs, also we need to reset the simulator anyway
-	echo "- Setting the device to \"$SIM_DEVICE\""
 	echo "- Resetting simulator content and settings"
-
-	"$SCRIPT_DIR/simulator-set" --device "$SIM_DEVICE" --version "$SIM_VERSION" --reset
+	if [[ -n "$SIM_DEVICE" ]]; then
+		"$SCRIPT_DIR/simulator-set" --device "$SIM_DEVICE" --version "$SIM_VERSION" --reset
+	else
+		"$SCRIPT_DIR/simulator-set" --id "$SIM_ID" --reset
+	fi
 	if [ $? -ne 0 ]; then
 		echo "\nERROR: Could not configure the simulator."
 		cleanup_and_exit 1
@@ -525,16 +525,6 @@ if [[ -z $VERBOSE_LOGGING ]] || ! $VERBOSE_LOGGING; then
 	defaults write com.apple.dt.InstrumentsCLI UIAVerboseLogging 4096
 fi
 
-# If `-login_password` was specified (i.e. the user has not yet pre-authorized `instruments`)
-# attempt to authorize instruments using the password
-if [[ -n "$LOGIN_PASSWORD" ]]; then
-	# First attempt to authorize `instruments` when it is launched: 
-	# in the background, monitor for, and dismiss, the dialog it shows
-	osascript "$SCRIPT_DIR/authorize_instruments.scpt" "$LOGIN_PASSWORD" &
-	# Track pid to be killed when the parent script ends
-	AUTHORIZE_INSTRUMENTS_PID=$!
-fi
-
 launch_instruments () {	
 	# Second attempt to authorize `instruments` ourselves
 	# (in case the dialog does not show, as in certain CI environments 
@@ -551,8 +541,10 @@ launch_instruments () {
 	device_string() {
 		if [[ -n "$HW_ID" ]]; then
 			echo "$HW_ID"
+		elif [[ -n "$SIM_ID" ]]; then
+			echo "$SIM_ID"
 		else
-			if [[ "$(xcrun xcodebuild -version | head -n 1)" == "Xcode 6"* ]]; then
+			if [ $IS_XCODE6 ]; then
 				echo "$SIM_DEVICE ($SIM_VERSION Simulator)"
 			else
 				echo "$SIM_DEVICE - Simulator - iOS $SIM_VERSION"
@@ -560,7 +552,7 @@ launch_instruments () {
 		fi
 	}
 	
-	printf "$LOGIN_PASSWORD\n" | "$SCRIPT_DIR/subliminal-instrument.sh"\
+	"$SCRIPT_DIR/subliminal-instrument.sh"\
 		-D "$TRACE_FILE"\
 		$timeout_arg\
 		-w "$(device_string)"\
@@ -628,7 +620,7 @@ while ([ ! -e "$RESULT_LOG" ] || grep -qi "Please relaunch the tests" "$RESULT_L
 
 	# Reset the simulator/reinstall the app on the device 
 	# in case instruments installed the app and then aborted
-	if [[ -n "$SIM_DEVICE" ]]; then
+	if [[ -n "$SIM_DEVICE" || -n "$SIM_ID" ]]; then
 		reset_simulator_or_device
 	else
 		reinstall_app_on_device
